# Site Information
site_name: Gary Innerarity
site_description: Gary Innerarity (OSPF2FULLSTACK) complete maintainer.
site_author: Gary Innerarity
site_url: https://garyinnerarity.com

# Configuration
docs_dir: docs

theme:
  name: material
  logo: ../assets/img/gary.jpg
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
  # palette:
  # - scheme: default
  #     primary: blue grey
  #     accent: red
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: blue grey
  #     accent: indigo
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode

# Plugins
plugins: 
  - search:
      lang: en
  - minify:
      minify_html: true
  # - blog:
  #     blog_dir: blog/posts/

# Navigation
nav:
  - Home:
      - index.md
  - blog:
      - blog/index.md